### ISSUE TITLE
7/6 Calendar Updates

### ISSUE THREAD

**Issue by jeffersongit** [rivetal/Sorenson#3]
FROM DANA: Please make the following updates and post a new PDF to ML:

1) Increase font size and send out updated word count to Dana and Donalda with the larger font.
2) Add links to the end of the text in the black bar.
3) Put a copyright statement on the calendar pages in addition to the revised s-bug in the arch. Also, we need to give attribution to Clare Cassidy (photographer) and Suzanne Stecker (design). Dana to send you the text.

**Comment by kyleiman** [comment]
This has been completed.

**Comment by kyleiman** [comment]
This item has been completed.
