### ISSUE TITLE
Unum Presentation

### ISSUE THREAD

**Issue by jeffersongit** [rivetal/Sorenson#5]
@kyleiman @blairtadams We have an "unveiling" on the 8th of August at 2pm. Here is what we need to have prepared for that meeting:

FROM ANN:
We would like you to prepare the two latest logos to present as options, however we need you to come up with a color other than the yellow/orange. Turns out, our competitor, “Z,” just introduced a new logo that uses a similar color. (You can check it out at www.zvrs.com)

FROM JEFF:
Once the logos are ready. Let's do a final review as a group on all the stuff to make sure we're happy with what we're bringing. Thanks!

**Comment by jeffersongit** [comment]
@kyleiman @blairtadams Here is the feedback for preparing the final Unum presentation. They would like to see these changes made by next week Wednesday.

[UnumUpdates.txt](https://github.com/rivetal/Sorenson/files/412236/UnumUpdates.txt)

![vrsii](https://cloud.githubusercontent.com/assets/17884163/17573468/c2ad89c0-5f17-11e6-9248-10ea8d54c1db.jpg)
![usa sorenson team at nsad](https://cloud.githubusercontent.com/assets/17884163/17573465/c2ac49f2-5f17-11e6-8381-c186bac6fe0c.jpg)
![lasvegas_social](https://cloud.githubusercontent.com/assets/17884163/17573469/c2adb5bc-5f17-11e6-8491-2c53041f59be.jpg)
![jacksonville_social](https://cloud.githubusercontent.com/assets/17884163/17573466/c2ad0c2a-5f17-11e6-9b80-bd697a93af00.jpg)
![charleston_wv_social](https://cloud.githubusercontent.com/assets/17884163/17573467/c2ad258e-5f17-11e6-9635-58aa5251ab3a.jpg)
![austin_social](https://cloud.githubusercontent.com/assets/17884163/17573470/c2bfc3e2-5f17-11e6-8ff7-800b120de774.jpg)
![screen shot 2016-08-09 at 4 18 32 pm](https://cloud.githubusercontent.com/assets/17884163/17573471/c2bfd332-5f17-11e6-9a0c-7529ef64131f.png)

**Comment by jeffersongit** [comment]
@kyleiman Here is a link to a video with instructions and copy:

Can you capture a screen grab from the video (link below) that we can use as one of the vlog images? Please capture a shot that is the most expressive – perhaps a black and white with a lot of motion – or one of the split-screen B/W and color shots. I will be getting the captioning on it tomorrow and can supply the copy to accompany it.

<iframe src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FaimediaAUS%2Fvideos%2F10153947977174220%2F&show_text=0&width=560" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>

Here’s the to accompany the black-and-white/split screen video from which you will pull a screen grab. Here’s what it should say:
 
1.         Sign Language Can Express Ideas in Ways Words Cannot
With sign language, you see the world through different eyes. You have a different perception of things. I remember when I was younger, my Deaf brother and I had the ability to see what we were imagining because we could create it on our hands. It is powerful. Let me give you a quick example.

**Comment by kyleiman** [comment]
This has been completed.
